apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  # ToDo : 왜 이미지를 선언해야하는 거지,,? 튜토리얼에서는 안 보이는데,,, ㅇㅅㅇ,,
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.124.0
  mode: deployment # This configuration is omittable.
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    exporters:
      # Metrics
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: default
      # Traces
      jaeger:
        endpoint: jaeger-server:4317
        tls:
          insecure: true
      # Logs
      loki:
        endpoint: "http://loki:3100/otlp"
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ prometheus ]
        traces:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ jaeger ]
        logs:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ loki ]