apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.124.0 # Why applying this works only ?
  mode: deployment # This configuration is omittable.
  # ToDo : receivers, processors, exporters 에 대한 설정 처리하기
  # ToDo : receivers, processors, exporters 에 대한 설정 처리하기
  # ToDo : receivers, processors, exporters 에 대한 설정 처리하기
  # ToDo : receivers, processors, exporters 에 대한 설정 처리하기
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors: {}
    exporters:
      # Data sources: metrics
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: default
      # Data sources: traces
      otlp/jaeger:
        endpoint: jaeger-server:4317
        tls:
          cert_file: cert.pem
          key_file: cert-key.pem
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp/jaeger]