spring:
  application:
    name: otlp-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/otlp_demo
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 1000 #최적화 옵션
      hibernate.jdbc:
        time_zone: Asia/Seoul
        batch_size: 1000
        order_inserts: true
        order_updates: true
        auto_quote_keyword: true # 예약어 사용가능
        globally_quoted_identifiers: true # 예약어 사용가능
        show_sql: true # sql 로깅
        generate_statistics: true # 쿼리수행 통계
        format_sql: true # SQL문 정렬하여 출력
        highlight_sql: true # SQL문 색 부여
    open-in-view: false