create table consumed_choco_dao
(
    cc_idx            bigint generated by default as identity
        constraint pk_consumedchocodao
            primary key,
    uuid              bigint not null
        constraint fk_consumedchocodao_on_uuid
            references user_dao,
    ch_consumed_choco numeric
);

alter table consumed_choco_dao
    owner to postgres;

INSERT INTO public.consumed_choco_dao (cc_idx, uuid, ch_consumed_choco) VALUES (1, 3, 100);
INSERT INTO public.consumed_choco_dao (cc_idx, uuid, ch_consumed_choco) VALUES (2, 3, 100);
INSERT INTO public.consumed_choco_dao (cc_idx, uuid, ch_consumed_choco) VALUES (3, 3, 100);
INSERT INTO public.consumed_choco_dao (cc_idx, uuid, ch_consumed_choco) VALUES (4, 3, 20);
INSERT INTO public.consumed_choco_dao (cc_idx, uuid, ch_consumed_choco) VALUES (5, 3, 20);
INSERT INTO public.consumed_choco_dao (cc_idx, uuid, ch_consumed_choco) VALUES (6, 3, 20);
