create table earned_choco_dao
(
    ec_idx          bigint generated by default as identity
        constraint pk_earnedchocodao
            primary key,
    uuid            bigint not null
        constraint fk_earnedchocodao_on_uuid
            references user_dao,
    ch_earned_choco numeric
);

alter table earned_choco_dao
    owner to postgres;

INSERT INTO public.earned_choco_dao (ec_idx, uuid, ch_earned_choco) VALUES (1, 1, 100);
INSERT INTO public.earned_choco_dao (ec_idx, uuid, ch_earned_choco) VALUES (2, 1, 100);
INSERT INTO public.earned_choco_dao (ec_idx, uuid, ch_earned_choco) VALUES (3, 1, 100);
INSERT INTO public.earned_choco_dao (ec_idx, uuid, ch_earned_choco) VALUES (6, 1, 20);
INSERT INTO public.earned_choco_dao (ec_idx, uuid, ch_earned_choco) VALUES (7, 1, 20);
INSERT INTO public.earned_choco_dao (ec_idx, uuid, ch_earned_choco) VALUES (8, 1, 20);
