create table order_dao
(
    ord_idx     bigint generated by default as identity
        constraint pk_orderdao
            primary key,
    uuid        bigint not null
        constraint fk_orderdao_on_uuid
            references user_dao,
    prd_idx     bigint not null
        constraint fk_orderdao_on_prd_idx
            references product_dao,
    quantity    bigint,
    final_price numeric,
    ordered_at  timestamp
);

alter table order_dao
    owner to postgres;

INSERT INTO public.order_dao (ord_idx, uuid, prd_idx, quantity, final_price, ordered_at) VALUES (2, 3, 1, null, 100, '2025-05-20 13:22:03.400544');
INSERT INTO public.order_dao (ord_idx, uuid, prd_idx, quantity, final_price, ordered_at) VALUES (3, 3, 1, null, 100, '2025-05-20 13:22:40.732936');
INSERT INTO public.order_dao (ord_idx, uuid, prd_idx, quantity, final_price, ordered_at) VALUES (4, 3, 1, null, 100, '2025-05-20 15:16:17.859911');
INSERT INTO public.order_dao (ord_idx, uuid, prd_idx, quantity, final_price, ordered_at) VALUES (7, 3, 3, null, 20, '2025-05-30 11:29:20.613935');
INSERT INTO public.order_dao (ord_idx, uuid, prd_idx, quantity, final_price, ordered_at) VALUES (8, 3, 3, null, 20, '2025-05-30 11:34:27.260525');
INSERT INTO public.order_dao (ord_idx, uuid, prd_idx, quantity, final_price, ordered_at) VALUES (9, 3, 3, null, 20, '2025-05-30 11:38:24.229960');
