create table user_dao
(
    uuid         bigint generated by default as identity
        constraint pk_userdao
            primary key,
    name         varchar(255),
    phone_number varchar(255),
    last_login   timestamp,
    amount       numeric
);

comment on column user_dao.uuid is '고객 ID';

comment on column user_dao.name is '고객명';

comment on column user_dao.phone_number is '전화번호';

comment on column user_dao.last_login is '최근 로그인 날짜';

comment on column user_dao.amount is '잔액';

alter table user_dao
    owner to postgres;

INSERT INTO public.user_dao (uuid, name, phone_number, last_login, amount) VALUES (2, '김철수', null, null, 1000);
INSERT INTO public.user_dao (uuid, name, phone_number, last_login, amount) VALUES (3, '이은지', null, null, 640);
INSERT INTO public.user_dao (uuid, name, phone_number, last_login, amount) VALUES (1, '홍길동', null, null, 1360);
