create table user_dao
(
    uuid         bigint generated by default as identity
        constraint pk_userdao
        primary key,
    name         varchar(255),
    phone_number varchar(255),
    last_login   timestamp,
    amount       numeric
);

comment on column user_dao.uuid is '고객 ID';

comment on column user_dao.name is '고객명';

comment on column user_dao.phone_number is '전화번호';

comment on column user_dao.last_login is '최근 로그인 날짜';

comment on column user_dao.amount is '잔액';

alter table user_dao
    owner to postgres;

create table product_dao
(
    prd_idx    bigint not null
        constraint pk_productdao
            primary key,
    uuid       bigint not null
        constraint fk_productdao_on_uuid
            references user_dao,
    name       varchar(255),
    price      numeric,
    quantity   bigint,
    created_at timestamp,
    expired_at timestamp
);

comment on column product_dao.prd_idx is '상품 ID';

alter table product_dao
    owner to postgres;

create table order_dao
(
    ord_idx     bigint generated by default as identity
        constraint pk_orderdao
        primary key,
    uuid        bigint not null
        constraint fk_orderdao_on_uuid
            references user_dao,
    prd_idx     bigint not null
        constraint fk_orderdao_on_prd_idx
            references product_dao,
    quantity    bigint,
    final_price numeric,
    ordered_at  timestamp
);

alter table order_dao
    owner to postgres;

create table earned_choco_dao
(
    ec_idx          bigint generated by default as identity
        constraint pk_earnedchocodao
        primary key,
    uuid            bigint not null
        constraint fk_earnedchocodao_on_uuid
            references user_dao,
    ch_earned_choco numeric
);

alter table earned_choco_dao
    owner to postgres;

create table consumed_choco_dao
(
    cc_idx            bigint generated by default as identity
        constraint pk_consumedchocodao
        primary key,
    uuid              bigint not null
        constraint fk_consumedchocodao_on_uuid
            references user_dao,
    ch_consumed_choco numeric
);

alter table consumed_choco_dao
    owner to postgres;



INSERT INTO user_dao (uuid, name, phone_number, last_login, amount) VALUES (2, '김철수', null, null, 1000);
INSERT INTO user_dao (uuid, name, phone_number, last_login, amount) VALUES (3, '이은지', null, null, 800);
INSERT INTO user_dao (uuid, name, phone_number, last_login, amount) VALUES (1, '홍길동', null, null, 1200);

INSERT INTO product_dao (prd_idx, uuid, name, price, quantity, created_at, expired_at) VALUES (1, 1, '아이폰', 100, 3, '2025-05-20 13:06:15.000000', '2025-05-27 13:06:07.000000');
INSERT INTO product_dao (prd_idx, uuid, name, price, quantity, created_at, expired_at) VALUES (2, 1, '갤럭시폰', 90, 4, '2025-05-20 13:06:15.000000', '2025-05-27 13:06:07.000000');
INSERT INTO product_dao (prd_idx, uuid, name, price, quantity, created_at, expired_at) VALUES (3, 1, 'Go가이드북', 10, 100, '2025-05-20 13:06:15.000000', '2025-05-27 13:06:07.000000');
